[package]
name = "use-numerical"
description = "Utility-first approximate numerical helpers for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage = "https://github.com/RustUse/use-math"
documentation = "https://docs.rs/use-numerical"
keywords = ["math", "numerical", "approximation", "integration", "roots"]
categories = ["mathematics", "science"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
interval = ["dep:use-interval"]

[dependencies]
use-interval = { version = "0.0.7", path = "../use-interval", optional = true }

[lints]
workspace = true
